apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-backend
  namespace: cvm-wallets
spec:
  replicas: 1
  selector: { matchLabels: { app: wallet-backend } }
  template:
    metadata: { labels: { app: wallet-backend } }
    spec:
      serviceAccountName: wallet-sa
      containers:
      - name: backend
        image: wallet-backend:local
        imagePullPolicy: Never # with minikube's docker daemon
        env:
        - name: ATTESTER_URL
          value: http://cvm-attester.cvm-security.svc.cluster.local:5000/attest
        - name: TOKEN_AUD
          value: https://issuer.example/oidc
        - name: WALLET_INSTANCE
          value: default
        ports: [{ containerPort: 4000 }]
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-backend
  namespace: cvm-wallets
spec:
  selector: { app: wallet-backend }
  ports:
  - port: 8081
    targetPort: 4000
    protocol: TCP
  type: ClusterIP