# IMMERSE Verifier Service
# Logs are not handled here, they're emitted by the pod, see verifier's deployment or pod level logs.
apiVersion: v1
kind: Service
metadata:
  name: verifier
spec:
  type: NodePort
  selector:
    app: verifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32000